/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects. It is kept here so
// TypeScript works before the first local dev run.

